log:
  level: error

api:
  http: "127.0.0.1:18081"

plugins:
  - tag: browser_forward
    type: forward
    args:
      upstreams:
        - addr: "tcp://127.0.0.1:9"

  - tag: browser_reject
    type: sequence
    args:
      - exec: reject 3

  - tag: browser_tcp
    type: tcp_server
    args:
      entry: browser_reject
      listen: "127.0.0.1:15354"
      idle_timeout: 2
      enable_audit: true
