log:
  level: error
api:
  http: "127.0.0.1:__API_PORT__"
plugins:
  - tag: sequence_main
    type: sequence
    args:
      - matches: qname $blocklist
        exec: reject 3
      - exec: reject 0
  - tag: blocklist
    type: domain_set
    args:
      files:
        - rules/blocklist.txt
  - tag: whitelist
    type: domain_set
    args:
      files:
        - rules/whitelist.txt
  - tag: forward_main
    type: forward
    args:
      upstreams:
        - addr: "udp://127.0.0.1:25999"
  - tag: listener
    type: udp_server
    args:
      entry: sequence_main
      listen: "127.0.0.1:__DNS_PORT__"
      enable_audit: false
