//! Immutable input to the native managed configuration compiler.
//! Stored disabled records are retained as JSON values: unsupported data must
//! not disappear merely because the native profile cannot execute it.
use crate::config::ConfigError;
use serde::{Deserialize, Serialize};
use serde_json::{Value, json};
use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

pub const ROUTER_TAG: &str = "special_upstream_matcher";
pub const GENERATED_PATH: &str = "sub_config/special_groups.yaml";
const STATE_LIMIT: u64 = 1_048_576;
pub(crate) type StagedFiles = BTreeMap<PathBuf, Option<Vec<u8>>>;

/// Every canonical input read while compiling one managed candidate. Paths
/// remain lexical so a symlink retarget or an added formerly-missing optional
/// file is checked again before the transaction replaces canonical state.
#[derive(Clone, Debug, Default)]
pub(crate) struct CandidateInputSet {
    pub files: BTreeMap<PathBuf, Option<String>>,
}

impl CandidateInputSet {
    pub(crate) fn record_bytes(&mut self, path: &Path, bytes: &[u8]) -> Result<(), String> {
        self.record(path, Some(sha256(bytes)))
    }

    pub(crate) fn record_missing(&mut self, path: &Path) -> Result<(), String> {
        self.record(path, None)
    }

    fn record(&mut self, path: &Path, digest: Option<String>) -> Result<(), String> {
        let path = lexical_path(path);
        if let Some(previous) = self.files.get(&path) {
            if previous != &digest {
                return Err(format!(
                    "input changed while compiling candidate: {}",
                    path.display()
                ));
            }
        } else {
            self.files.insert(path, digest);
        }
        Ok(())
    }
}

pub(crate) fn reserved_tag(tag: &str) -> bool {
    tag == ROUTER_TAG
        || [
            "special_",
            "special_upstream_",
            "special_route_",
            "special_manual_",
            "cache_special_",
            "sequence_special_",
            "special_udp_server_",
            "special_tcp_server_",
        ]
        .iter()
        .any(|prefix| {
            tag.strip_prefix(prefix)
                .is_some_and(|tail| !tail.is_empty() && tail.bytes().all(|b| b.is_ascii_digit()))
        })
}

pub(crate) fn lexical_path(path: &Path) -> PathBuf {
    let mut output = PathBuf::new();
    for component in path.components() {
        match component {
            std::path::Component::CurDir => {}
            std::path::Component::ParentDir => {
                output.pop();
            }
            component => output.push(component.as_os_str()),
        }
    }
    output
}

#[derive(Clone, Debug, Deserialize, Serialize, Eq, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct SpecialGroup {
    pub slot: u32,
    pub name: String,
    #[serde(default)]
    pub listen_port: u16,
    #[serde(default)]
    pub custom_port_only: bool,
}

impl SpecialGroup {
    pub fn key(&self) -> String {
        format!("special_{}", self.slot)
    }
    pub fn view(&self) -> Value {
        json!({"slot":self.slot,"name":self.name,"listen_port":self.listen_port,
            "custom_port_only":self.custom_port_only,"key":self.key(),
            "upstream_plugin_tag":format!("special_upstream_{}",self.slot),
            "diversion_plugin_tag":format!("special_route_{}",self.slot),
            "manual_plugin_tag":format!("special_manual_{}",self.slot),
            "local_config":format!("srs/special_{}.json",self.slot),
            "manual_rule_path":format!("rule/special_{}.txt",self.slot)})
    }
}

#[derive(Clone, Debug)]
pub struct ManagedProfile {
    pub base_dir: PathBuf,
    /// Canonical root YAML that produced this managed runtime snapshot.
    /// In-memory configurations have no persistent root and leave it unset.
    pub config_path: Option<PathBuf>,
    pub groups: Vec<SpecialGroup>,
    pub overrides: BTreeMap<String, Vec<Value>>,
    pub sources: BTreeMap<u32, BTreeMap<String, Value>>,
    /// Exact optional manual-provider text captured with this candidate.
    pub manual_rules: BTreeMap<u32, String>,
    /// Exact generated input, compiled before resources can be prepared.
    pub generated_yaml: String,
    /// SHA-256 of precisely the generated bytes parsed by the compiler.
    pub generated_sha256: String,
}

fn fail(path: impl Into<String>, message: impl Into<String>) -> ConfigError {
    ConfigError::new(path, message)
}

fn read_json<T: serde::de::DeserializeOwned + Default>(
    path: &Path,
    inputs: Option<&mut CandidateInputSet>,
) -> Result<T, ConfigError> {
    let display = path.display().to_string();
    let file_path = path.to_path_buf();
    let read = crate::transaction::blocking_io(move || {
        let metadata = std::fs::metadata(&file_path)?;
        if metadata.len() > STATE_LIMIT {
            return Err(std::io::Error::other("managed state exceeds byte limit"));
        }
        std::fs::read(file_path)
    })
    .map_err(|error| fail(display.clone(), error.to_string()))?;
    let bytes = match read {
        Ok(bytes) => bytes,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            if let Some(inputs) = inputs {
                inputs
                    .record_missing(path)
                    .map_err(|reason| fail(display.clone(), reason))?;
            }
            return Ok(T::default());
        }
        Err(error) => return Err(fail(display, error.to_string())),
    };
    if let Some(inputs) = inputs {
        inputs
            .record_bytes(path, &bytes)
            .map_err(|reason| fail(path.display().to_string(), reason))?;
    }
    serde_json::from_slice(&bytes).map_err(|e| {
        fail(
            path.display().to_string(),
            format!("invalid managed JSON: {e}"),
        )
    })
}

fn read_candidate_json<T: serde::de::DeserializeOwned + Default>(
    path: &Path,
    files: &StagedFiles,
    inputs: &mut CandidateInputSet,
) -> Result<T, ConfigError> {
    match files.get(path) {
        Some(None) => Ok(T::default()),
        Some(Some(bytes)) => {
            if bytes.len() as u64 > STATE_LIMIT {
                return Err(fail(
                    path.display().to_string(),
                    "managed state exceeds byte limit",
                ));
            }
            serde_json::from_slice(bytes).map_err(|error| {
                fail(
                    path.display().to_string(),
                    format!("invalid managed JSON: {error}"),
                )
            })
        }
        None => read_json(path, Some(inputs)),
    }
}

pub fn normalize_groups(groups: &mut [SpecialGroup]) -> Result<(), ConfigError> {
    let (mut slots, mut names, mut ports) = (BTreeSet::new(), BTreeSet::new(), BTreeSet::new());
    for group in groups.iter_mut() {
        group.name = group.name.trim().to_owned();
        if group.slot < 50 || !slots.insert(group.slot) {
            return Err(fail("special_groups", "invalid or duplicate slot"));
        }
        if group.name.is_empty() || !names.insert(group.name.to_lowercase()) {
            return Err(fail("special_groups", "empty or duplicate group name"));
        }
        if group.listen_port == 53 {
            return Err(fail("special_groups", "listen port 53 is reserved"));
        }
        if group.listen_port != 0 && !ports.insert(group.listen_port) {
            return Err(fail("special_groups", "duplicate listen port"));
        }
        if group.listen_port == 0 {
            group.custom_port_only = false;
        }
    }
    groups.sort_by_key(|g| g.slot);
    Ok(())
}

fn harmless(value: &Value) -> bool {
    value.is_null() || value == false || value == 0 || value == ""
}

/// Translate the UI schema to the existing forward compiler; never dial here.
pub fn forward_entries(entries: &[Value], path: &str) -> Result<Vec<Value>, ConfigError> {
    let mut tags = BTreeSet::new();
    let mut enabled = Vec::new();
    for item in entries {
        let object = item
            .as_object()
            .ok_or_else(|| fail(path, "upstream entry must be an object"))?;
        let tag = object
            .get("tag")
            .and_then(Value::as_str)
            .filter(|v| !v.trim().is_empty())
            .ok_or_else(|| fail(path, "upstream tag is required"))?;
        if !tags.insert(tag) {
            return Err(fail(path, "duplicate upstream entry tag"));
        }
        let active = object
            .get("enabled")
            .and_then(Value::as_bool)
            .ok_or_else(|| fail(path, "enabled must be boolean"))?;
        if !active {
            continue;
        }
        let protocol = object
            .get("protocol")
            .and_then(Value::as_str)
            .ok_or_else(|| fail(path, "upstream protocol is required"))?;
        let scheme = match protocol {
            "udp" => "udp",
            "tcp" => "tcp",
            "dot" | "tls" => "tls",
            "doh" | "https" => "https",
            _ => return Err(fail(path, "unsupported upstream protocol")),
        };
        let address = object
            .get("addr")
            .and_then(Value::as_str)
            .filter(|s| !s.is_empty())
            .ok_or_else(|| fail(path, "upstream addr is required"))?;
        let mut address = if let Some((prefix, _)) = address.split_once("://") {
            let expected = match prefix {
                "dot" => "tls",
                "doh" => "https",
                value => value,
            };
            if expected != scheme {
                return Err(fail(path, "upstream address scheme mismatch"));
            }
            format!("{scheme}://{}", address.split_once("://").unwrap().1)
        } else {
            format!("{scheme}://{address}")
        };
        if scheme == "https" {
            let mut url = url::Url::parse(&address).map_err(|e| fail(path, e.to_string()))?;
            if url.path() == "/" || url.path().is_empty() {
                url.set_path("/dns-query");
            }
            address = url.to_string();
        }
        let mut output = serde_json::Map::new();
        output.insert("tag".into(), json!(tag));
        output.insert("addr".into(), json!(address));
        for (key, value) in object {
            match key.as_str() {
                "tag" | "enabled" | "protocol" | "addr" => {}
                "dial_addr"
                | "bootstrap"
                | "bootstrap_version"
                | "upstream_query_timeout"
                | "insecure_skip_verify" => {
                    if !harmless(value) {
                        output.insert(key.clone(), value.clone());
                    }
                }
                "idle_timeout" | "enable_pipeline" | "enable_http3" | "socks5"
                | "use_socks_proxy" | "so_mark" | "bind_to_device" | "max_conns" | "account_id"
                | "access_key_id" | "access_key_secret" | "server_addr" | "ecs_client_ip"
                | "ecs_client_mask"
                    if harmless(value) => {}
                _ => return Err(fail(path, format!("unsupported upstream option `{key}`"))),
            }
        }
        enabled.push(Value::Object(output));
    }
    if enabled.is_empty() {
        return Err(fail(path, "at least one enabled upstream is required"));
    }
    Ok(enabled)
}

fn source_file(
    value: &Value,
    name: &str,
    group: &SpecialGroup,
) -> Result<Option<String>, ConfigError> {
    let path = format!("srs/{}.json:{name}", group.key());
    let object = value
        .as_object()
        .ok_or_else(|| fail(&path, "source must be an object"))?;
    if object.get("enabled").and_then(Value::as_bool) == Some(false) {
        return Ok(None);
    }
    if object.get("enabled").and_then(Value::as_bool) != Some(true) {
        return Err(fail(&path, "source enabled must be boolean"));
    }
    // Disabled records above are opaque retained state. Enabled records must
    // not silently discard unknown semantics, even if an unknown value looks
    // like a harmless default; only documented fields can be normalized.
    for key in object.keys() {
        if !matches!(
            key.as_str(),
            "enabled" | "name" | "type" | "url" | "auto_update" | "enable_regexp" | "files"
        ) {
            return Err(fail(&path, format!("unsupported source option `{key}`")));
        }
    }
    if name.trim().is_empty()
        || object.get("name").and_then(Value::as_str) != Some(name)
        || object.get("type").and_then(Value::as_str) != Some(group.key().as_str())
    {
        return Err(fail(&path, "source name/type does not match catalog"));
    }
    for key in ["url", "auto_update", "enable_regexp"] {
        if object.get(key).is_some_and(|v| !harmless(v)) {
            return Err(fail(&path, format!("unsupported source option `{key}`")));
        }
    }
    let file = object
        .get("files")
        .and_then(Value::as_str)
        .filter(|s| !s.is_empty())
        .ok_or_else(|| fail(&path, "one local text file is required"))?;
    if Path::new(file).extension().and_then(|s| s.to_str()) != Some("txt") {
        return Err(fail(path, "only local .txt sources are supported"));
    }
    Ok(Some(file.to_owned()))
}

impl ManagedProfile {
    pub fn load(base: &Path) -> Result<Self, ConfigError> {
        Self::load_with_files_and_inputs(
            base,
            &StagedFiles::new(),
            &mut CandidateInputSet::default(),
        )
    }

    pub(crate) fn load_with_files_and_inputs(
        base: &Path,
        files: &StagedFiles,
        inputs: &mut CandidateInputSet,
    ) -> Result<Self, ConfigError> {
        let canonicalize_path = if base.as_os_str().is_empty() {
            PathBuf::from(".")
        } else {
            base.to_path_buf()
        };
        let base_dir =
            crate::transaction::blocking_io(move || std::fs::canonicalize(canonicalize_path))
                .map_err(|error| fail("native_management", error.to_string()))?
                .map_err(|error| fail("native_management", error.to_string()))?;
        let mut groups: Vec<SpecialGroup> = read_candidate_json(
            &base_dir.join("webinfo/special_upstream_groups.json"),
            files,
            inputs,
        )?;
        normalize_groups(&mut groups)?;
        let overrides = read_candidate_json(
            &base_dir.join("webinfo/upstream_overrides.json"),
            files,
            inputs,
        )?;
        let mut sources = BTreeMap::new();
        for group in &groups {
            sources.insert(
                group.slot,
                read_candidate_json(
                    &base_dir.join(format!("srs/{}.json", group.key())),
                    files,
                    inputs,
                )?,
            );
        }
        let mut manual_rules = BTreeMap::new();
        for group in &groups {
            manual_rules.insert(
                group.slot,
                read_manual_text(&base_dir, group.slot, files, inputs)?,
            );
        }
        let mut profile = Self {
            base_dir,
            config_path: None,
            groups,
            overrides,
            sources,
            manual_rules,
            generated_yaml: String::new(),
            generated_sha256: String::new(),
        };
        profile.generated_yaml = profile.generate_with_files(files, Some(inputs))?;
        profile.generated_sha256 = sha256(profile.generated_yaml.as_bytes());
        Ok(profile)
    }

    pub fn generate(&self) -> Result<String, ConfigError> {
        self.generate_with_files(&StagedFiles::new(), None)
    }

    fn generate_with_files(
        &self,
        staged: &StagedFiles,
        mut inputs: Option<&mut CandidateInputSet>,
    ) -> Result<String, ConfigError> {
        let mut plugins = Vec::new();
        let mut routes = Vec::new();
        for group in &self.groups {
            let slot = group.slot;
            let files = self
                .sources
                .get(&slot)
                .into_iter()
                .flat_map(|sources| sources.iter())
                .map(|(name, source)| source_file(source, name, group))
                .collect::<Result<Vec<_>, _>>()?
                .into_iter()
                .flatten()
                .map(|file| self.base_dir.join(file).to_string_lossy().into_owned())
                .collect::<Vec<_>>();
            let manual = self.base_dir.join(format!("rule/special_{slot}.txt"));
            // An absent newly created manual provider is empty. Existing files
            // are compiled strictly by the ordinary domain_set parser.
            let manual_exists = match staged.get(&manual) {
                Some(bytes) => bytes.is_some(),
                None => {
                    let path = manual.clone();
                    crate::transaction::blocking_io(move || path.try_exists())
                        .and_then(|result| result)
                        .map_err(|error| fail(manual.display().to_string(), error.to_string()))?
                }
            };
            if !manual_exists && staged.get(&manual).is_none() {
                if let Some(inputs) = inputs.as_deref_mut() {
                    inputs
                        .record_missing(&manual)
                        .map_err(|reason| fail(manual.display().to_string(), reason))?;
                }
            }
            let manual_files: Vec<String> = if manual_exists {
                vec![manual.to_string_lossy().into_owned()]
            } else {
                vec![]
            };
            let upstream = format!("special_upstream_{slot}");
            let entries = match self.overrides.get(&upstream) {
                Some(entries) => forward_entries(entries, &upstream)?,
                None => vec![json!({"addr":"udp://223.5.5.5","tag":format!("{upstream}_default")})],
            };
            plugins.push(json!({"tag":format!("special_route_{slot}"),"type":"domain_set","args":{"files":files}}));
            plugins.push(json!({"tag":format!("special_manual_{slot}"),"type":"domain_set","args":{"files":manual_files}}));
            plugins.push(json!({"tag":format!("cache_special_{slot}"),"type":"cache","args":{"size":20_000_000,"lazy_cache_ttl":259_200_000,"dump_interval":36000,"dump_file":self.base_dir.join(format!("cache/cache_special_{slot}.dump"))}}));
            plugins.push(json!({"tag":upstream,"type":"forward","args":{"concurrent":2,"upstreams":entries}}));
            plugins.push(json!({"tag":format!("sequence_special_{slot}"),"type":"sequence","args":[
                {"exec":format!("flow_setter group=special_{slot} sequence=sequence_special_{slot}")},
                {"exec":format!("$cache_special_{slot}")},
                {"exec":format!("$special_upstream_{slot}")},
                {"exec":"cname_remover"}]}));
            if !group.custom_port_only {
                routes.push(json!({"matches":format!("qname $special_route_{slot} $special_manual_{slot}"),"exec":[format!("$sequence_special_{slot}"),"exit"]}));
            }
            if group.listen_port != 0 {
                for transport in ["udp", "tcp"] {
                    let mut args = json!({"listen":format!("0.0.0.0:{}",group.listen_port),"entry":format!("sequence_special_{slot}"),"enable_audit":true});
                    if transport == "tcp" {
                        args["idle_timeout"] = json!(10);
                    }
                    plugins.push(json!({"tag":format!("special_{transport}_server_{slot}"),"type":format!("{transport}_server"),"args":args}));
                }
            }
        }
        // Empty sequence is represented by a return instruction, preserving
        // the caller's explicit default path without inventing a default peer.
        routes.push(json!({"exec":"return"}));
        plugins.push(json!({"tag":ROUTER_TAG,"type":"sequence","args":routes}));
        yaml_serde::to_string(&json!({"plugins":plugins}))
            .map_err(|e| fail(GENERATED_PATH, e.to_string()))
    }
}

fn read_manual_text(
    base_dir: &Path,
    slot: u32,
    staged: &StagedFiles,
    inputs: &mut CandidateInputSet,
) -> Result<String, ConfigError> {
    let relative = PathBuf::from(format!("rule/special_{slot}.txt"));
    let path = base_dir.join(&relative);
    let display = path.display().to_string();
    let bytes = match staged.get(&path) {
        Some(Some(bytes)) => Some(bytes.clone()),
        Some(None) => None,
        None => {
            let read_path = path.clone();
            let worker_display = display.clone();
            let result =
                crate::transaction::blocking_io(move || match std::fs::metadata(&read_path) {
                    Ok(metadata) if metadata.len() > crate::policy::POLICY_BYTES_LIMIT as u64 => {
                        Err(std::io::Error::other("rule file exceeds byte limit"))
                    }
                    Ok(_) => std::fs::read(read_path).map(Some),
                    Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(None),
                    Err(error) => Err(error),
                })
                .map_err(|error| fail(worker_display.clone(), error.to_string()))?
                .map_err(|error| fail(worker_display, error.to_string()))?;
            match result {
                Some(bytes) => {
                    inputs
                        .record_bytes(&path, &bytes)
                        .map_err(|reason| fail(display.clone(), reason))?;
                    Some(bytes)
                }
                None => {
                    inputs
                        .record_missing(&path)
                        .map_err(|reason| fail(display.clone(), reason))?;
                    None
                }
            }
        }
    };
    match bytes {
        Some(bytes) => String::from_utf8(bytes)
            .map_err(|error| fail(display, format!("enabled rule file is not UTF-8: {error}"))),
        None => Ok(String::new()),
    }
}

pub(crate) fn sha256(bytes: &[u8]) -> String {
    ring::digest::digest(&ring::digest::SHA256, bytes)
        .as_ref()
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect()
}
