//! Scoped durable state ownership for the opt-in native management profile.
use fs2::FileExt;
use serde::{Deserialize, Serialize};
use std::fs::{File, OpenOptions};
use std::io::{Read, Write};
use std::path::{Path, PathBuf};
use std::sync::OnceLock;
use std::sync::mpsc::{SyncSender, sync_channel};

const JOURNAL_DIR: &str = "webinfo/native_management.transaction";
const STAGING_DIR: &str = "webinfo/native_management.staging";
const RETIRED_DIR: &str = "webinfo/native_management.retired";
const MAX_FILES: usize = 64;
const MAX_FILE_BYTES: u64 = 64 * 1024 * 1024;
const MAX_TOTAL_BYTES: usize = 256 * 1024 * 1024;
const MAX_JOURNAL_BYTES: u64 = 1024 * 1024;
const MAX_INPUTS: usize = 4096;
const MAX_INPUT_BYTES: u64 = 256 * 1024 * 1024;
const MAX_INPUT_TOTAL_BYTES: u64 = 1024 * 1024 * 1024;

type IoJob = Box<dyn FnOnce() + Send + 'static>;

struct BlockingIoWorker {
    sender: SyncSender<IoJob>,
}

static BLOCKING_IO_WORKER: OnceLock<Result<BlockingIoWorker, String>> = OnceLock::new();

std::thread_local! {
    static ON_BLOCKING_IO_WORKER: std::cell::Cell<bool> = const { std::cell::Cell::new(false) };
}

/// Run filesystem work on one dedicated worker with one queued operation.
/// Compiler results stay on the current thread because the native graph is Rc-owned.
pub(crate) fn blocking_io<T, F>(operation: F) -> std::io::Result<T>
where
    T: Send + 'static,
    F: FnOnce() -> T + Send + 'static,
{
    if ON_BLOCKING_IO_WORKER.with(std::cell::Cell::get) {
        return std::panic::catch_unwind(std::panic::AssertUnwindSafe(operation))
            .map_err(|_| std::io::Error::other("blocking I/O worker operation panicked"));
    }
    let worker = BLOCKING_IO_WORKER.get_or_init(|| {
        let (sender, receiver) = sync_channel::<IoJob>(1);
        std::thread::Builder::new()
            .name("mosdns-managed-io".into())
            .spawn(move || {
                while let Ok(job) = receiver.recv() {
                    ON_BLOCKING_IO_WORKER.with(|inside| inside.set(true));
                    job();
                    ON_BLOCKING_IO_WORKER.with(|inside| inside.set(false));
                }
            })
            .map(|_| BlockingIoWorker { sender })
            .map_err(|error| error.to_string())
    });
    let worker = worker
        .as_ref()
        .map_err(|reason| std::io::Error::other(reason.clone()))?;
    let (send, receive) = sync_channel(0);
    worker
        .sender
        .send(Box::new(move || {
            let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(operation))
                .map_err(|_| std::io::Error::other("blocking I/O worker operation panicked"));
            let _ = send.send(result);
        }))
        .map_err(|_| std::io::Error::other("blocking I/O worker stopped"))?;
    receive
        .recv()
        .map_err(|_| std::io::Error::other("blocking I/O worker stopped"))?
}

#[derive(Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct JournalFile {
    path: PathBuf,
    old_sha256: Option<String>,
    new_sha256: Option<String>,
}

#[derive(Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct JournalInput {
    path: PathBuf,
    sha256: Option<String>,
}

#[derive(Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct Journal {
    schema_version: u32,
    transaction_id: String,
    old_generation: u64,
    new_generation: u64,
    files: Vec<JournalFile>,
    #[serde(default)]
    inputs: Vec<JournalInput>,
}

#[derive(Debug)]
pub enum TransactionError {
    Io(std::io::Error),
    Busy(std::io::Error),
    Invalid(String),
    Conflict(PathBuf),
    CommitAmbiguous(String),
}
impl std::fmt::Display for TransactionError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Io(error) => write!(f, "managed transaction: {error}"),
            Self::Busy(error) => write!(f, "managed state has another writer: {error}"),
            Self::Invalid(reason) => write!(f, "invalid managed journal: {reason}"),
            Self::Conflict(path) => {
                write!(f, "managed file changed externally: {}", path.display())
            }
            Self::CommitAmbiguous(reason) => {
                write!(f, "commit marker outcome is ambiguous: {reason}")
            }
        }
    }
}
impl std::error::Error for TransactionError {}
impl From<std::io::Error> for TransactionError {
    fn from(error: std::io::Error) -> Self {
        Self::Io(error)
    }
}

/// One process owns this guard until all runtime mutation/cleanup has ended.
pub struct ManagedStore {
    root: PathBuf,
    _lock: File,
}

/// Exact generated bytes accompany the graph compiled from candidate inputs.
pub struct CompiledCandidate {
    config: Option<crate::config::CompiledConfig>,
    persistence: CandidatePersistence,
}

/// Sendable, disk-only candidate state. The Rc-owned compiled graph remains on
/// the host thread while this value moves to the bounded I/O worker.
pub struct CandidatePersistence {
    root: PathBuf,
    files: Vec<(PathBuf, Option<Vec<u8>>)>,
    cache_dump_replacements: Vec<PathBuf>,
    baseline: std::collections::BTreeMap<PathBuf, Option<String>>,
    inputs: std::collections::BTreeMap<PathBuf, Option<String>>,
}

impl CandidatePersistence {
    pub(crate) fn replace_cache_dumps(&mut self, paths: Vec<PathBuf>) {
        self.cache_dump_replacements = paths;
    }
}
impl CompiledCandidate {
    #[must_use]
    pub fn config(&self) -> &crate::config::CompiledConfig {
        self.config
            .as_ref()
            .expect("compiled candidate graph already moved into runtime preparation")
    }
    #[must_use]
    pub fn files(&self) -> &[(PathBuf, Option<Vec<u8>>)] {
        &self.persistence.files
    }
    #[cfg(test)]
    pub(crate) fn persistence(&self) -> &CandidatePersistence {
        &self.persistence
    }
    /// Splits the Rc-owned runtime graph from its sendable durable artifacts.
    pub(crate) fn into_parts(mut self) -> (crate::config::CompiledConfig, CandidatePersistence) {
        let config = self
            .config
            .take()
            .expect("compiled candidate graph is consumed once");
        (config, self.persistence)
    }
}
impl ManagedStore {
    pub fn prepare_candidate(
        &mut self,
        old: u64,
        new: u64,
        candidate: &CandidatePersistence,
    ) -> Result<(), TransactionError> {
        if candidate.root != self.root {
            return Err(TransactionError::Invalid("foreign candidate root".into()));
        }
        let mut files = candidate.files.clone();
        let mut baseline = candidate.baseline.clone();
        let mut cache_dump_paths = std::collections::BTreeSet::new();
        if !candidate.cache_dump_replacements.is_empty() {
            let empty_dump = crate::cache_dump::encode(&[])
                .map_err(|error| TransactionError::Invalid(error.to_string()))?;
            for absolute in &candidate.cache_dump_replacements {
                let path = absolute.strip_prefix(&self.root).map_err(|_| {
                    TransactionError::Invalid(format!(
                        "impacted cache dump is outside the managed state root: {}",
                        absolute.display()
                    ))
                })?;
                let path = crate::special_groups::lexical_path(path);
                self.validate_cache_dump_path(&path)?;
                if files.iter().any(|(candidate, _)| *candidate == path) {
                    return Err(TransactionError::Invalid(format!(
                        "candidate already writes impacted cache dump {}",
                        path.display()
                    )));
                }
                let current = self.read_canonical(&path)?;
                baseline.insert(path.clone(), hash_optional(current.as_deref()));
                cache_dump_paths.insert(path.clone());
                files.push((path, Some(empty_dump.clone())));
            }
        }
        for (path, expected) in &baseline {
            if hash_optional(self.read_canonical(path)?.as_deref()) != *expected {
                return Err(TransactionError::Conflict(path.clone()));
            }
        }
        self.verify_inputs(&candidate.inputs, &std::collections::BTreeSet::new())?;
        let inputs = candidate
            .inputs
            .iter()
            .map(|(path, sha256)| JournalInput {
                path: path.clone(),
                sha256: sha256.clone(),
            })
            .collect();
        self.prepare_with_inputs(old, new, files, inputs, &cache_dump_paths)?;
        let journal = self.load_journal()?;
        for file in &journal.files {
            if baseline.get(&file.path) != Some(&file.old_sha256) {
                self.cleanup(&journal)?;
                return Err(TransactionError::Conflict(file.path.clone()));
            }
        }
        if let Err(error) = self.verify_journal_inputs(&journal, &std::collections::BTreeSet::new())
        {
            self.cleanup(&journal)?;
            return Err(error);
        }
        Ok(())
    }
    pub fn compile_candidate(
        &self,
        config_path: &Path,
        changes: Vec<(PathBuf, Option<Vec<u8>>)>,
    ) -> Result<CompiledCandidate, TransactionError> {
        let parent = config_path
            .parent()
            .filter(|path| !path.as_os_str().is_empty())
            .unwrap_or_else(|| Path::new("."));
        if canonicalize_path(parent)? != self.root {
            return Err(TransactionError::Invalid(
                "candidate configuration root must remain frozen".into(),
            ));
        }
        let config_path = canonicalize_path(config_path)?;
        if config_path.parent() != Some(self.root.as_path()) {
            return Err(TransactionError::Invalid(
                "candidate configuration root must remain frozen".into(),
            ));
        }
        let mut staged = crate::special_groups::StagedFiles::new();
        let mut baseline = std::collections::BTreeMap::new();
        let mut inputs = crate::special_groups::CandidateInputSet::default();
        for (path, bytes) in &changes {
            self.validate_candidate_path(path)?;
            baseline.insert(
                path.clone(),
                hash_optional(self.read_canonical(path)?.as_deref()),
            );
            if staged.insert(self.root.join(path), bytes.clone()).is_some() {
                return Err(TransactionError::Invalid("duplicate candidate path".into()));
            }
        }
        let generated_path = PathBuf::from(crate::special_groups::GENERATED_PATH);
        if !baseline.contains_key(&generated_path) {
            baseline.insert(
                generated_path.clone(),
                hash_optional(self.read_canonical(&generated_path)?.as_deref()),
            );
        }
        let mut profile = crate::special_groups::ManagedProfile::load_with_files_and_inputs(
            &self.root,
            &staged,
            &mut inputs,
        )
        .map_err(|error| TransactionError::Invalid(error.to_string()))?;
        profile.config_path = Some(config_path.clone());
        let generated = profile.generated_yaml.as_bytes().to_vec();
        if staged
            .get(&self.root.join(&generated_path))
            .is_some_and(|bytes| bytes.as_deref() != Some(generated.as_slice()))
        {
            return Err(TransactionError::Invalid(
                "candidate generated YAML does not match its complete profile".into(),
            ));
        }
        let yaml = crate::config::load_yaml_with_inputs(&config_path, &mut inputs)
            .map_err(|error| TransactionError::Invalid(error.to_string()))?;
        let config =
            crate::config::compile_candidate_yaml(&yaml, &self.root, profile, &staged, &mut inputs)
                .map_err(|error| TransactionError::Invalid(error.to_string()))?;
        let mut files = changes;
        if !files.iter().any(|(path, _)| *path == generated_path) {
            files.push((generated_path, Some(generated)));
        }
        let candidate_root = config
            .managed_profile
            .as_ref()
            .map(|profile| profile.base_dir.clone())
            .ok_or_else(|| TransactionError::Invalid("managed candidate profile missing".into()))?;
        Ok(CompiledCandidate {
            config: Some(config),
            persistence: CandidatePersistence {
                root: candidate_root,
                files,
                cache_dump_replacements: Vec::new(),
                baseline,
                inputs: inputs.files,
            },
        })
    }
    pub(crate) fn has_pending(root: &Path) -> bool {
        [JOURNAL_DIR, STAGING_DIR, RETIRED_DIR]
            .iter()
            .any(|path| std::fs::symlink_metadata(root.join(path)).is_ok())
    }
    /// Called only after the committed generation's old owners have retired.
    pub fn finish_retirement(&mut self) -> Result<(), TransactionError> {
        let journal = self.load_journal()?;
        if !self.has_commit(&journal)? {
            return Err(TransactionError::Invalid(
                "cannot retire an uncommitted transaction".into(),
            ));
        }
        self.cleanup(&journal)
    }
    /// Durable point of no return. Errors from marker write/rename/fsync are
    /// ambiguous: the coordinator must stop admission and require recovery.
    pub fn mark_committed(&mut self) -> Result<(), TransactionError> {
        let journal = self.load_journal()?;
        self.validate_artifacts(&journal)?;
        let written_paths = journal
            .files
            .iter()
            .map(|file| crate::special_groups::lexical_path(&self.root.join(&file.path)))
            .collect();
        self.verify_journal_inputs(&journal, &written_paths)?;
        for file in &journal.files {
            if hash_optional(self.read_canonical(&file.path)?.as_deref()) != file.new_sha256 {
                return Err(TransactionError::Conflict(file.path.clone()));
            }
        }
        let dir = self.root.join(JOURNAL_DIR);
        let encoded = read_bounded(&dir.join("journal.json"), MAX_JOURNAL_BYTES)?;
        let marker = (|| {
            durable_write(
                &dir.join("commit.tmp"),
                crate::special_groups::sha256(&encoded).as_bytes(),
            )?;
            std::fs::rename(dir.join("commit.tmp"), dir.join("commit"))?;
            file_boundary()?;
            sync_dir(&dir)
        })();
        marker.map_err(|error| TransactionError::CommitAmbiguous(error.to_string()))
    }
    /// Stages immutable new bytes and original backups before canonical writes.
    /// Call only on the coordinator's bounded blocking worker.
    pub fn prepare(
        &mut self,
        old: u64,
        new: u64,
        changes: Vec<(PathBuf, Option<Vec<u8>>)>,
    ) -> Result<(), TransactionError> {
        self.prepare_with_inputs(
            old,
            new,
            changes,
            Vec::new(),
            &std::collections::BTreeSet::new(),
        )
    }

    fn prepare_with_inputs(
        &mut self,
        old: u64,
        new: u64,
        changes: Vec<(PathBuf, Option<Vec<u8>>)>,
        inputs: Vec<JournalInput>,
        cache_dump_paths: &std::collections::BTreeSet<PathBuf>,
    ) -> Result<(), TransactionError> {
        if [JOURNAL_DIR, STAGING_DIR, RETIRED_DIR]
            .iter()
            .any(|path| self.root.join(path).exists())
        {
            return Err(TransactionError::Invalid(
                "unfinished transaction requires recovery".into(),
            ));
        }
        if new
            != old
                .checked_add(1)
                .ok_or_else(|| TransactionError::Invalid("generation overflow".into()))?
            || changes.is_empty()
            || changes.len() > MAX_FILES
        {
            return Err(TransactionError::Invalid(
                "invalid generation or file count".into(),
            ));
        }
        let mut files = Vec::with_capacity(changes.len());
        let mut originals = Vec::with_capacity(changes.len());
        let mut seen = std::collections::BTreeSet::new();
        let mut total = 0usize;
        if inputs.len() > MAX_INPUTS {
            return Err(TransactionError::Invalid(
                "candidate input set exceeds path limit".into(),
            ));
        }
        for (path, bytes) in &changes {
            if cache_dump_paths.contains(path) {
                self.validate_cache_dump_path(path)?;
            } else {
                self.validate_path(path)?;
            }
            if !seen.insert(path.clone()) {
                return Err(TransactionError::Invalid("duplicate canonical path".into()));
            }
            let original = self.read_canonical(path)?;
            for value in [original.as_ref(), bytes.as_ref()].into_iter().flatten() {
                if value.len() as u64 > MAX_FILE_BYTES {
                    return Err(TransactionError::Invalid(
                        "artifact exceeds byte limit".into(),
                    ));
                }
                total = total
                    .checked_add(value.len())
                    .ok_or_else(|| TransactionError::Invalid("artifact size overflow".into()))?;
            }
            if total > MAX_TOTAL_BYTES {
                return Err(TransactionError::Invalid(
                    "transaction exceeds byte limit".into(),
                ));
            }
            files.push(JournalFile {
                path: path.clone(),
                old_sha256: hash_optional(original.as_deref()),
                new_sha256: hash_optional(bytes.as_deref()),
            });
            originals.push(original);
        }
        let mut random = [0u8; 16];
        getrandom::fill(&mut random)
            .map_err(|error| TransactionError::Invalid(error.to_string()))?;
        let transaction_id = random.iter().map(|byte| format!("{byte:02x}")).collect();
        let journal = Journal {
            schema_version: 1,
            transaction_id,
            old_generation: old,
            new_generation: new,
            files,
            inputs,
        };
        let encoded = serde_json::to_vec(&journal)
            .map_err(|error| TransactionError::Invalid(error.to_string()))?;
        if encoded.len() as u64 > MAX_JOURNAL_BYTES {
            return Err(TransactionError::Invalid(
                "candidate journal exceeds byte limit".into(),
            ));
        }
        let dir = self.root.join(STAGING_DIR);
        std::fs::create_dir(&dir)?;
        file_boundary()?;
        sync_dir(dir.parent().expect("transaction has parent"))?;
        for (index, ((_, bytes), original)) in changes.iter().zip(&originals).enumerate() {
            if let Some(bytes) = bytes {
                durable_write(&dir.join(format!("{index}.new")), bytes)?;
            }
            if let Some(bytes) = original {
                durable_write(&dir.join(format!("{index}.old")), bytes)?;
            }
        }
        durable_write(&dir.join("journal.tmp"), &encoded)?;
        std::fs::rename(dir.join("journal.tmp"), dir.join("journal.json"))?;
        file_boundary()?;
        sync_dir(&dir)?;
        std::fs::rename(&dir, self.root.join(JOURNAL_DIR))?;
        file_boundary()?;
        sync_dir(dir.parent().expect("transaction has parent"))?;
        Ok(())
    }
    /// Admission and impacted persistence gates must remain closed across this
    /// operation, marker publication, and the preallocated runtime swap.
    pub fn replace_prepared(&mut self) -> Result<(), TransactionError> {
        let journal = self.load_journal()?;
        if self.has_commit(&journal)? {
            return Err(TransactionError::Invalid(
                "committed transaction cannot replace or roll back".into(),
            ));
        }
        self.validate_artifacts(&journal)?;
        let written_paths = journal
            .files
            .iter()
            .map(|file| crate::special_groups::lexical_path(&self.root.join(&file.path)))
            .collect();
        if let Err(error) = self.verify_journal_inputs(&journal, &written_paths) {
            self.cleanup(&journal)?;
            return Err(error);
        }
        for file in &journal.files {
            if hash_optional(self.read_canonical(&file.path)?.as_deref()) != file.old_sha256 {
                // The complete preflight finishes before the first canonical
                // write. Discarding this unused preparation preserves edits
                // made by an external writer; undo recovery must not overwrite them.
                self.cleanup(&journal)?;
                return Err(TransactionError::Conflict(file.path.clone()));
            }
        }
        self.apply_files(&journal, false)
    }

    /// Restore the entire old state before any runtime is compiled or bound.
    pub fn recover(&mut self) -> Result<(), TransactionError> {
        // Neither directory can authorize canonical writes. Publication of a
        // complete prepared journal and retirement each use one directory rename.
        for name in [STAGING_DIR, RETIRED_DIR] {
            self.cleanup_directory(&self.root.join(name))?;
        }
        let dir = self.root.join(JOURNAL_DIR);
        reject_symlink(&dir)?;
        if !dir.exists() {
            return Ok(());
        }
        let journal = self.load_journal()?;
        self.validate_artifacts(&journal)?;
        let old = !self.has_commit(&journal)?;
        self.apply_files(&journal, old)?;
        self.cleanup(&journal)
    }

    fn has_commit(&self, _journal: &Journal) -> Result<bool, TransactionError> {
        let dir = self.root.join(JOURNAL_DIR);
        match read_bounded(&dir.join("commit"), 64) {
            Ok(marker) => {
                let encoded = read_bounded(&dir.join("journal.json"), MAX_JOURNAL_BYTES)?;
                if marker != crate::special_groups::sha256(&encoded).as_bytes() {
                    return Err(TransactionError::Invalid(
                        "commit marker does not identify this journal".into(),
                    ));
                }
                Ok(true)
            }
            Err(TransactionError::Io(error)) if error.kind() == std::io::ErrorKind::NotFound => {
                Ok(false)
            }
            Err(error) => Err(error),
        }
    }

    fn load_journal(&self) -> Result<Journal, TransactionError> {
        let dir = self.root.join(JOURNAL_DIR);
        reject_symlink(&dir)?;
        let encoded = read_bounded(&dir.join("journal.json"), MAX_JOURNAL_BYTES)?;
        let journal: Journal = serde_json::from_slice(&encoded)
            .map_err(|error| TransactionError::Invalid(error.to_string()))?;
        if journal.schema_version != 1
            || journal.transaction_id.len() != 32
            || !journal
                .transaction_id
                .bytes()
                .all(|byte| byte.is_ascii_hexdigit())
            || journal.old_generation.checked_add(1) != Some(journal.new_generation)
            || journal.files.is_empty()
            || journal.files.len() > MAX_FILES
            || journal.inputs.len() > MAX_INPUTS
        {
            return Err(TransactionError::Invalid("invalid journal header".into()));
        }
        let mut seen = std::collections::BTreeSet::new();
        for file in &journal.files {
            self.validate_journal_path(&file.path)?;
            if !seen.insert(file.path.clone()) {
                return Err(TransactionError::Invalid("duplicate journal path".into()));
            }
            for hash in [file.old_sha256.as_ref(), file.new_sha256.as_ref()]
                .into_iter()
                .flatten()
            {
                if hash.len() != 64 || !hash.bytes().all(|byte| byte.is_ascii_hexdigit()) {
                    return Err(TransactionError::Invalid("invalid artifact digest".into()));
                }
            }
        }
        seen.clear();
        for input in &journal.inputs {
            if !input.path.is_absolute()
                || !seen.insert(crate::special_groups::lexical_path(&input.path))
            {
                return Err(TransactionError::Invalid(
                    "invalid or duplicate candidate input path".into(),
                ));
            }
            if let Some(hash) = &input.sha256 {
                if hash.len() != 64 || !hash.bytes().all(|byte| byte.is_ascii_hexdigit()) {
                    return Err(TransactionError::Invalid(
                        "invalid candidate input digest".into(),
                    ));
                }
            }
        }
        Ok(journal)
    }

    fn verify_inputs(
        &self,
        inputs: &std::collections::BTreeMap<PathBuf, Option<String>>,
        ignored: &std::collections::BTreeSet<PathBuf>,
    ) -> Result<(), TransactionError> {
        if inputs.len() > MAX_INPUTS {
            return Err(TransactionError::Invalid(
                "candidate input set exceeds path limit".into(),
            ));
        }
        if inputs.keys().any(|path| !path.is_absolute()) {
            return Err(TransactionError::Invalid(
                "candidate input path must be absolute".into(),
            ));
        }
        let inputs = inputs
            .iter()
            .map(|(path, sha256)| JournalInput {
                path: path.clone(),
                sha256: sha256.clone(),
            })
            .collect::<Vec<_>>();
        self.verify_input_records(&inputs, ignored)
    }

    fn verify_journal_inputs(
        &self,
        journal: &Journal,
        ignored: &std::collections::BTreeSet<PathBuf>,
    ) -> Result<(), TransactionError> {
        self.verify_input_records(&journal.inputs, ignored)
    }

    fn verify_input_records(
        &self,
        inputs: &[JournalInput],
        ignored: &std::collections::BTreeSet<PathBuf>,
    ) -> Result<(), TransactionError> {
        let mut total = 0u64;
        for input in inputs {
            let path = crate::special_groups::lexical_path(&input.path);
            if ignored.contains(&path) {
                continue;
            }
            let actual = hash_input(&input.path, &mut total)?;
            if actual != input.sha256 {
                return Err(TransactionError::Conflict(input.path.clone()));
            }
        }
        Ok(())
    }

    fn validate_artifacts(&self, journal: &Journal) -> Result<(), TransactionError> {
        let mut total = 0usize;
        for (index, file) in journal.files.iter().enumerate() {
            for (suffix, expected) in [("old", &file.old_sha256), ("new", &file.new_sha256)] {
                if let Some(expected) = expected {
                    let bytes = read_bounded(
                        &self
                            .root
                            .join(JOURNAL_DIR)
                            .join(format!("{index}.{suffix}")),
                        MAX_FILE_BYTES,
                    )?;
                    total = total.checked_add(bytes.len()).ok_or_else(|| {
                        TransactionError::Invalid("artifact size overflow".into())
                    })?;
                    if total > MAX_TOTAL_BYTES || crate::special_groups::sha256(&bytes) != *expected
                    {
                        return Err(TransactionError::Invalid(
                            "corrupt or oversized artifact".into(),
                        ));
                    }
                }
            }
        }
        Ok(())
    }

    fn apply_files(&self, journal: &Journal, old: bool) -> Result<(), TransactionError> {
        for (index, file) in journal.files.iter().enumerate() {
            self.validate_journal_path(&file.path)?;
            let target = self.root.join(&file.path);
            let parent = target.parent().expect("validated managed path has parent");
            create_managed_parent(&self.root, parent)?;
            let temp = parent.join(format!(".native-management-{}.tmp", journal.transaction_id));
            reject_symlink(&temp)?;
            match std::fs::remove_file(&temp) {
                Ok(()) => file_boundary()?,
                Err(error) if error.kind() == std::io::ErrorKind::NotFound => (),
                Err(error) => return Err(error.into()),
            }
            let expected = if old {
                &file.old_sha256
            } else {
                &file.new_sha256
            };
            if expected.is_some() {
                let suffix = if old { "old" } else { "new" };
                let bytes = read_bounded(
                    &self
                        .root
                        .join(JOURNAL_DIR)
                        .join(format!("{index}.{suffix}")),
                    MAX_FILE_BYTES,
                )?;
                durable_write(&temp, &bytes)?;
                std::fs::rename(&temp, &target)?;
                file_boundary()?;
            } else {
                match std::fs::remove_file(&target) {
                    Ok(()) => file_boundary()?,
                    Err(error) if error.kind() == std::io::ErrorKind::NotFound => (),
                    Err(error) => return Err(error.into()),
                }
            }
            sync_dir(parent)?;
        }
        Ok(())
    }

    fn cleanup(&self, _journal: &Journal) -> Result<(), TransactionError> {
        let dir = self.root.join(JOURNAL_DIR);
        let retired = self.root.join(RETIRED_DIR);
        reject_symlink(&retired)?;
        if retired.exists() {
            return Err(TransactionError::Invalid(
                "unfinished retirement cleanup".into(),
            ));
        }
        std::fs::rename(&dir, &retired)?;
        file_boundary()?;
        sync_dir(dir.parent().expect("transaction has parent"))?;
        self.cleanup_directory(&retired)
    }

    fn cleanup_directory(&self, dir: &Path) -> Result<(), TransactionError> {
        reject_symlink(dir)?;
        if !dir.exists() {
            return Ok(());
        }
        let mut paths = Vec::new();
        for entry in std::fs::read_dir(dir)? {
            let entry = entry?;
            let name = entry.file_name();
            let name = name
                .to_str()
                .ok_or_else(|| TransactionError::Invalid("non-UTF8 transaction artifact".into()))?;
            let numbered = name.split_once('.').is_some_and(|(index, suffix)| {
                matches!(suffix, "old" | "new")
                    && index.parse::<usize>().is_ok_and(|index| index < MAX_FILES)
            });
            if paths.len() >= 2 * MAX_FILES + 4
                || !entry.file_type()?.is_file()
                || (!numbered
                    && !matches!(
                        name,
                        "journal.tmp" | "journal.json" | "commit.tmp" | "commit"
                    ))
            {
                return Err(TransactionError::Invalid(
                    "unexpected staging/retirement artifact".into(),
                ));
            }
            paths.push(entry.path());
        }
        for path in paths {
            std::fs::remove_file(path)?;
            file_boundary()?;
        }
        sync_dir(dir)?;
        std::fs::remove_dir(dir)?;
        file_boundary()?;
        sync_dir(dir.parent().expect("transaction has parent"))
    }

    fn read_canonical(&self, path: &Path) -> Result<Option<Vec<u8>>, TransactionError> {
        if is_cache_dump_artifact(path) {
            self.validate_cache_dump_path(path)?;
        } else {
            self.validate_path(path)?;
        }
        let canonical = self.root.join(path);
        let read = blocking_io(move || read_bounded(&canonical, MAX_FILE_BYTES))?;
        match read {
            Ok(bytes) => Ok(Some(bytes)),
            Err(TransactionError::Io(error)) if error.kind() == std::io::ErrorKind::NotFound => {
                Ok(None)
            }
            Err(error) => Err(error),
        }
    }

    fn validate_path(&self, path: &Path) -> Result<(), TransactionError> {
        let root = self.root.clone();
        let path = path.to_path_buf();
        blocking_io(move || validate_managed_path(&root, &path, false))?
    }

    fn validate_candidate_path(&self, path: &Path) -> Result<(), TransactionError> {
        if is_cache_dump_artifact(path) {
            return Err(TransactionError::Invalid(
                "cache dumps are owned by the cache lifecycle".into(),
            ));
        }
        self.validate_path(path)
    }

    fn validate_journal_path(&self, path: &Path) -> Result<(), TransactionError> {
        if is_cache_dump_artifact(path) {
            self.validate_cache_dump_path(path)
        } else {
            self.validate_path(path)
        }
    }

    fn validate_cache_dump_path(&self, path: &Path) -> Result<(), TransactionError> {
        if !is_cache_dump_artifact(path) {
            return Err(TransactionError::Invalid(
                "cache dump path must be cache/<name>.dump".into(),
            ));
        }
        let root = self.root.clone();
        let path = path.to_path_buf();
        blocking_io(move || validate_managed_path(&root, &path, true))?
    }

    pub fn open(root: &Path) -> Result<Self, TransactionError> {
        let root = root.to_path_buf();
        blocking_io(move || Self::open_inner(&root))?
    }

    fn open_inner(root: &Path) -> Result<Self, TransactionError> {
        let root = std::fs::canonicalize(root)?;
        let webinfo = root.join("webinfo");
        reject_symlink(&webinfo)?;
        std::fs::create_dir_all(&webinfo)?;
        reject_symlink(&webinfo.join("native_management.lock"))?;
        let lock = OpenOptions::new()
            .create(true)
            .truncate(false)
            .read(true)
            .write(true)
            .open(webinfo.join("native_management.lock"))?;
        lock.try_lock_exclusive().map_err(|error| {
            if error.kind() == std::io::ErrorKind::WouldBlock {
                TransactionError::Busy(error)
            } else {
                TransactionError::Io(error)
            }
        })?;
        Ok(Self { root, _lock: lock })
    }
    #[must_use]
    pub fn root(&self) -> &Path {
        &self.root
    }
}

fn validate_managed_path(
    root: &Path,
    path: &Path,
    allow_cache_dump: bool,
) -> Result<(), TransactionError> {
    let parts: Vec<_> = path.components().collect();
    if parts.len() != 2
        || parts
            .iter()
            .any(|part| !matches!(part, std::path::Component::Normal(_)))
    {
        return Err(TransactionError::Invalid(
            "managed path must be scoped and relative".into(),
        ));
    }
    let text = path
        .to_str()
        .ok_or_else(|| TransactionError::Invalid("non-UTF8 managed path".into()))?;
    let numbered = |prefix: &str, suffix: &str| {
        text.strip_prefix(prefix)
            .and_then(|value| value.strip_suffix(suffix))
            .and_then(|value| value.parse::<u32>().ok())
            .is_some_and(|slot| slot >= 50)
    };
    if !(matches!(
        text,
        "webinfo/special_upstream_groups.json"
            | "webinfo/upstream_overrides.json"
            | "sub_config/special_groups.yaml"
    ) || numbered("srs/special_", ".json")
        || numbered("rule/special_", ".txt")
        || (allow_cache_dump && is_cache_dump_artifact(path)))
    {
        return Err(TransactionError::Invalid(
            "path is not a native managed artifact".into(),
        ));
    }
    let mut cursor = root.to_path_buf();
    for part in parts {
        cursor.push(part.as_os_str());
        reject_symlink(&cursor)?;
    }
    Ok(())
}

fn is_cache_dump_artifact(path: &Path) -> bool {
    let mut components = path.components();
    let Some(std::path::Component::Normal(directory)) = components.next() else {
        return false;
    };
    let Some(std::path::Component::Normal(file)) = components.next() else {
        return false;
    };
    if components.next().is_some() || directory != "cache" {
        return false;
    }
    file.to_str()
        .is_some_and(|file| file.len() > ".dump".len() && file.ends_with(".dump"))
}

fn hash_optional(bytes: Option<&[u8]>) -> Option<String> {
    bytes.map(crate::special_groups::sha256)
}

fn canonicalize_path(path: &Path) -> Result<PathBuf, TransactionError> {
    let path = path.to_path_buf();
    Ok(blocking_io(move || std::fs::canonicalize(path))??)
}

fn hash_input(path: &Path, total: &mut u64) -> Result<Option<String>, TransactionError> {
    let path = path.to_path_buf();
    let mut next_total = *total;
    let (hash, next_total) = blocking_io(move || {
        let hash = hash_input_inner(&path, &mut next_total)?;
        Ok::<_, TransactionError>((hash, next_total))
    })??;
    *total = next_total;
    Ok(hash)
}

fn hash_input_inner(path: &Path, total: &mut u64) -> Result<Option<String>, TransactionError> {
    let metadata = match std::fs::metadata(path) {
        Ok(metadata) => metadata,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(None),
        Err(error) => return Err(error.into()),
    };
    if !metadata.is_file() || metadata.len() > MAX_INPUT_BYTES {
        return Err(TransactionError::Conflict(path.to_path_buf()));
    }
    let mut file = File::open(path)?;
    if !file.metadata()?.is_file() {
        return Err(TransactionError::Conflict(path.to_path_buf()));
    }
    let mut context = ring::digest::Context::new(&ring::digest::SHA256);
    let mut buffer = [0u8; 64 * 1024];
    loop {
        let count = file.read(&mut buffer)?;
        if count == 0 {
            break;
        }
        *total = total
            .checked_add(count as u64)
            .ok_or_else(|| TransactionError::Conflict(path.to_path_buf()))?;
        if *total > MAX_INPUT_TOTAL_BYTES {
            return Err(TransactionError::Conflict(path.to_path_buf()));
        }
        context.update(&buffer[..count]);
    }
    let digest = context.finish();
    let mut output = String::with_capacity(64);
    const HEX: &[u8; 16] = b"0123456789abcdef";
    for byte in digest.as_ref() {
        output.push(HEX[usize::from(byte >> 4)] as char);
        output.push(HEX[usize::from(byte & 0x0f)] as char);
    }
    Ok(Some(output))
}

fn read_bounded(path: &Path, limit: u64) -> Result<Vec<u8>, TransactionError> {
    reject_symlink(path)?;
    let file = File::open(path)?;
    let metadata = file.metadata()?;
    if !metadata.is_file() || metadata.len() > limit {
        return Err(TransactionError::Invalid(
            "invalid artifact type or byte limit".into(),
        ));
    }
    let mut bytes = Vec::new();
    file.take(limit + 1).read_to_end(&mut bytes)?;
    if bytes.len() as u64 > limit {
        return Err(TransactionError::Invalid(
            "artifact exceeded byte limit during read".into(),
        ));
    }
    Ok(bytes)
}

fn durable_write(path: &Path, bytes: &[u8]) -> Result<(), TransactionError> {
    reject_symlink(path)?;
    let mut file = OpenOptions::new().create_new(true).write(true).open(path)?;
    file.write_all(bytes)?;
    file_boundary()?;
    file.sync_all()?;
    file_boundary()?;
    Ok(())
}

fn sync_dir(path: &Path) -> Result<(), TransactionError> {
    reject_symlink(path)?;
    File::open(path)?.sync_all()?;
    file_boundary()?;
    Ok(())
}

#[cfg(test)]
std::thread_local! {
    static IO_FAIL_AFTER: std::cell::Cell<Option<usize>> = const { std::cell::Cell::new(None) };
    static IO_PAUSE_PATH: std::cell::RefCell<Option<PathBuf>> = const { std::cell::RefCell::new(None) };
    static IO_COMMITTED: std::cell::Cell<bool> = const { std::cell::Cell::new(false) };
}

// System-boundary fault injection is compiled only into the test harness.
fn file_boundary() -> Result<(), TransactionError> {
    #[cfg(test)]
    IO_FAIL_AFTER.with(|fault| {
        if let Some(remaining) = fault.get() {
            fault.set(remaining.checked_sub(1));
            if remaining == 1 {
                let pause = IO_PAUSE_PATH.with(|path| path.borrow().clone());
                if let Some(path) = pause {
                    let committed = IO_COMMITTED.with(std::cell::Cell::get);
                    std::fs::write(
                        path.with_extension("tmp"),
                        if committed {
                            b"committed".as_slice()
                        } else {
                            b"prepared".as_slice()
                        },
                    )?;
                    std::fs::rename(path.with_extension("tmp"), path)?;
                    loop {
                        std::thread::park();
                    }
                }
                return Err(TransactionError::Io(std::io::Error::other(
                    "injected filesystem boundary failure",
                )));
            }
        }
        Ok(())
    })?;
    Ok(())
}

fn create_managed_parent(root: &Path, path: &Path) -> Result<(), TransactionError> {
    reject_symlink(path)?;
    if !path.exists() {
        std::fs::create_dir(path)?;
        sync_dir(root)?;
    }
    Ok(())
}

fn reject_symlink(path: &Path) -> Result<(), TransactionError> {
    match std::fs::symlink_metadata(path) {
        Ok(metadata) if metadata.file_type().is_symlink() => Err(std::io::Error::new(
            std::io::ErrorKind::InvalidInput,
            "managed state cannot contain symbolic links",
        )
        .into()),
        Ok(_) => Ok(()),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(error) => Err(error.into()),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // flock owners are inherited briefly by concurrent fork/exec probes.
    // Serialize this module's process proofs and owner-drop/reopen assertions.
    static PROCESS_PROBE_GATE: std::sync::Mutex<()> = std::sync::Mutex::new(());

    #[test]
    fn bounded_io_worker_serializes_filesystem_jobs_on_one_named_thread() {
        use std::sync::atomic::{AtomicUsize, Ordering};

        let active = std::sync::Arc::new(AtomicUsize::new(0));
        let peak = std::sync::Arc::new(AtomicUsize::new(0));
        let mut jobs = Vec::new();
        for _ in 0..8 {
            let active = active.clone();
            let peak = peak.clone();
            jobs.push(std::thread::spawn(move || {
                blocking_io(move || {
                    assert_eq!(std::thread::current().name(), Some("mosdns-managed-io"));
                    let now = active.fetch_add(1, Ordering::SeqCst) + 1;
                    peak.fetch_max(now, Ordering::SeqCst);
                    std::thread::sleep(std::time::Duration::from_millis(2));
                    active.fetch_sub(1, Ordering::SeqCst);
                })
                .unwrap();
            }));
        }
        for job in jobs {
            job.join().unwrap();
        }
        assert_eq!(peak.load(Ordering::SeqCst), 1);
    }

    #[test]
    fn external_edit_after_candidate_compile_is_not_accepted_as_backup_baseline() {
        let _process_gate = PROCESS_PROBE_GATE.lock().unwrap();
        let root =
            std::env::temp_dir().join(format!("native-candidate-conflict-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(root.join("webinfo")).unwrap();
        let path = root.join("config.yaml");
        std::fs::write(
            &path,
            include_str!("../../../docs/rust/examples/native-managed-empty/config.yaml"),
        )
        .unwrap();
        let groups = PathBuf::from("webinfo/special_upstream_groups.json");
        std::fs::write(root.join(&groups), b"[]").unwrap();
        let mut owner = ManagedStore::open(&root).unwrap();
        let candidate = owner
            .compile_candidate(&path, vec![(groups.clone(), Some(b"[]".to_vec()))])
            .unwrap();
        std::fs::write(root.join(&groups), b"external edit").unwrap();
        assert!(
            matches!(
                owner.prepare_candidate(0, 1, candidate.persistence()),
                Err(TransactionError::Conflict(_))
            ),
            "compile-to-prepare changes must conflict"
        );
        assert!(!root.join(JOURNAL_DIR).exists());
        assert!(!root.join(STAGING_DIR).exists());
        assert_eq!(std::fs::read(root.join(&groups)).unwrap(), b"external edit");
        drop(owner);
        std::fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn candidate_rejects_changes_to_every_compiled_file_dependency() {
        let _process_gate = PROCESS_PROBE_GATE.lock().unwrap();
        for (name, changed_path, replacement) in [
            (
                "root-yaml",
                "config.yaml",
                b"# externally edited config\n".as_slice(),
            ),
            (
                "included-yaml",
                "parts/extra.yaml",
                b"plugins: []\n".as_slice(),
            ),
            (
                "upstream-overrides-json",
                "webinfo/upstream_overrides.json",
                b"{\"external\":[]}\n".as_slice(),
            ),
            (
                "query-only-rule",
                "rules/query_only.txt",
                b"full:changed.test\n".as_slice(),
            ),
            (
                "hosts-policy-rule",
                "rules/hosts.txt",
                b"policy.example 192.0.2.55\n".as_slice(),
            ),
            ("ip-set-rule", "rules/ip.txt", b"192.0.2.99/32\n".as_slice()),
            (
                "response-ip-rule",
                "rules/response-ip.txt",
                b"192.0.2.101/32\n".as_slice(),
            ),
            (
                "optional-ip-file-created",
                "rules/optional-ip.txt",
                b"192.0.2.100/32\n".as_slice(),
            ),
        ] {
            let root = std::env::temp_dir().join(format!(
                "native-candidate-input-{name}-{}",
                std::process::id()
            ));
            let _ = std::fs::remove_dir_all(&root);
            std::fs::create_dir_all(root.join("webinfo")).unwrap();
            std::fs::create_dir_all(root.join("parts")).unwrap();
            std::fs::create_dir_all(root.join("rules")).unwrap();
            let path = root.join("config.yaml");
            let yaml = include_str!("../../../docs/rust/examples/native-managed-empty/config.yaml")
                .replace("plugins:\n", "include:\n  - parts/extra.yaml\nplugins:\n");
            std::fs::write(&path, yaml).unwrap();
            std::fs::write(
                root.join("parts/extra.yaml"),
                concat!(
                    "plugins:\n",
                    "  - tag: query_only\n    type: domain_set\n    args: {files: [../rules/query_only.txt]}\n",
                    "  - tag: policy_hosts\n    type: hosts\n    args: {files: [../rules/hosts.txt]}\n",
                    "  - tag: policy_ips\n    type: ip_set\n    args: {files: [../rules/ip.txt]}\n",
                    "  - tag: optional_policy_ips\n    type: ip_set\n    args: {files: [../rules/optional-ip.txt]}\n",
                    "  - tag: response_probe\n    type: sequence\n    args:\n      - matches: 'resp_ip &../rules/response-ip.txt'\n        exec: accept\n",
                ),
            )
            .unwrap();
            std::fs::write(root.join("rules/query_only.txt"), b"full:original.test\n").unwrap();
            std::fs::write(root.join("rules/hosts.txt"), b"policy.example 192.0.2.1\n").unwrap();
            std::fs::write(root.join("rules/ip.txt"), b"192.0.2.1/32\n").unwrap();
            std::fs::write(root.join("rules/response-ip.txt"), b"192.0.2.1/32\n").unwrap();
            std::fs::write(root.join("webinfo/special_upstream_groups.json"), b"[]").unwrap();
            std::fs::write(root.join("webinfo/upstream_overrides.json"), b"{}\n").unwrap();

            let mut owner = ManagedStore::open(&root).unwrap();
            let groups = PathBuf::from("webinfo/special_upstream_groups.json");
            let candidate = owner
                .compile_candidate(&path, vec![(groups, Some(b"[]".to_vec()))])
                .unwrap();
            std::fs::write(root.join(changed_path), replacement).unwrap();
            let conflict = matches!(
                owner.prepare_candidate(0, 1, candidate.persistence()),
                Err(TransactionError::Conflict(_))
            );
            // Keep a failed RED run from leaving a prepared journal behind.
            owner.recover().unwrap();
            drop(owner);
            std::fs::remove_dir_all(root).unwrap();
            assert!(
                conflict,
                "candidate must detect an external edit to {changed_path}"
            );
        }
    }

    #[test]
    fn candidate_rejects_creation_of_absent_manual_dependency() {
        let _process_gate = PROCESS_PROBE_GATE.lock().unwrap();
        let root = std::env::temp_dir().join(format!(
            "native-candidate-manual-created-{}",
            std::process::id()
        ));
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(root.join("webinfo")).unwrap();
        std::fs::create_dir_all(root.join("rule")).unwrap();
        let config = root.join("config.yaml");
        std::fs::write(
            &config,
            include_str!("../../../docs/rust/examples/native-managed-empty/config.yaml"),
        )
        .unwrap();
        std::fs::write(
            root.join("webinfo/special_upstream_groups.json"),
            br#"[{"slot":50,"name":"group"}]"#,
        )
        .unwrap();
        std::fs::write(
            root.join("webinfo/upstream_overrides.json"),
            br#"{"special_upstream_50":[{"tag":"local","enabled":true,"protocol":"udp","addr":"127.0.0.1:15455"}]}"#,
        )
        .unwrap();

        let mut owner = ManagedStore::open(&root).unwrap();
        let groups = PathBuf::from("webinfo/special_upstream_groups.json");
        let candidate = owner
            .compile_candidate(
                &config,
                vec![(groups, Some(br#"[{"slot":50,"name":"group"}]"#.to_vec()))],
            )
            .unwrap();
        let manual = root.join("rule/special_50.txt");
        std::fs::write(&manual, b"full:created-after-compile.test\n").unwrap();

        let result = owner.prepare_candidate(0, 1, candidate.persistence());
        let rejected = matches!(result, Err(TransactionError::Conflict(_)));
        owner.recover().unwrap();
        assert!(
            rejected,
            "candidate must detect creation of an optional manual input after compile"
        );
        assert!(!root.join(JOURNAL_DIR).exists());
        assert!(!root.join(STAGING_DIR).exists());
        assert_eq!(
            std::fs::read(manual).unwrap(),
            b"full:created-after-compile.test\n"
        );
        drop(owner);
        std::fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn prepared_candidate_rechecks_dependencies_before_canonical_replacement() {
        let _process_gate = PROCESS_PROBE_GATE.lock().unwrap();
        let root = std::env::temp_dir().join(format!(
            "native-candidate-prepared-input-conflict-{}",
            std::process::id()
        ));
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(root.join("webinfo")).unwrap();
        std::fs::create_dir_all(root.join("parts")).unwrap();
        std::fs::create_dir_all(root.join("rules")).unwrap();
        let config = root.join("config.yaml");
        let yaml = include_str!("../../../docs/rust/examples/native-managed-empty/config.yaml")
            .replace("plugins:\n", "include:\n  - parts/extra.yaml\nplugins:\n");
        std::fs::write(&config, yaml).unwrap();
        std::fs::write(
            root.join("parts/extra.yaml"),
            "plugins:\n  - tag: query_only\n    type: domain_set\n    args: {files: [../rules/query_only.txt]}\n",
        )
        .unwrap();
        let rule_path = root.join("rules/query_only.txt");
        std::fs::write(&rule_path, b"full:original.test\n").unwrap();
        let groups = PathBuf::from("webinfo/special_upstream_groups.json");
        std::fs::write(root.join(&groups), b"[]").unwrap();

        let mut owner = ManagedStore::open(&root).unwrap();
        let candidate = owner
            .compile_candidate(&config, vec![(groups.clone(), Some(b"[]".to_vec()))])
            .unwrap();
        owner
            .prepare_candidate(0, 1, candidate.persistence())
            .unwrap();
        assert!(root.join(JOURNAL_DIR).exists());

        std::fs::write(&rule_path, b"full:external.test\n").unwrap();
        assert!(matches!(
            owner.replace_prepared(),
            Err(TransactionError::Conflict(path)) if path == rule_path
        ));
        assert!(!root.join(JOURNAL_DIR).exists());
        assert!(!root.join(STAGING_DIR).exists());
        assert_eq!(std::fs::read(root.join(&groups)).unwrap(), b"[]");
        assert!(!root.join(crate::special_groups::GENERATED_PATH).exists());
        assert_eq!(std::fs::read(&rule_path).unwrap(), b"full:external.test\n");
        drop(owner);
        std::fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn candidate_owned_text_updates_every_referencing_immutable_provider() {
        let _process_gate = PROCESS_PROBE_GATE.lock().unwrap();
        let root =
            std::env::temp_dir().join(format!("native-candidate-shared-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(root.join("webinfo")).unwrap();
        std::fs::create_dir_all(root.join("rule")).unwrap();
        let path = root.join("config.yaml");
        let yaml = include_str!("../../../docs/rust/examples/native-managed-empty/config.yaml").replace("plugins:\n","plugins:\n  - tag: shared_text\n    type: domain_set\n    args: {files: [rule/special_50.txt]}\n");
        std::fs::write(&path, yaml).unwrap();
        std::fs::write(
            root.join("webinfo/special_upstream_groups.json"),
            br#"[{"slot":50,"name":"group"}]"#,
        )
        .unwrap();
        std::fs::write(root.join("webinfo/upstream_overrides.json"),br#"{"special_upstream_50":[{"tag":"local","enabled":true,"protocol":"udp","addr":"127.0.0.1:15455"}]}"#).unwrap();
        std::fs::write(root.join("rule/special_50.txt"), b"full:old.test\n").unwrap();
        let owner = ManagedStore::open(&root).unwrap();
        let candidate = owner
            .compile_candidate(
                &path,
                vec![(
                    PathBuf::from("rule/special_50.txt"),
                    Some(b"full:new.test\n".to_vec()),
                )],
            )
            .unwrap();
        for tag in ["special_manual_50", "shared_text"] {
            let provider = candidate.config().domain_set(tag).unwrap();
            assert!(
                provider.matches("new.test"),
                "{tag} must compile candidate bytes"
            );
            assert!(
                !provider.matches("old.test"),
                "{tag} must discard previous bytes"
            );
        }
        assert_eq!(
            std::fs::read(root.join("rule/special_50.txt")).unwrap(),
            b"full:old.test\n"
        );
        drop(owner);
        std::fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn candidate_compiles_exact_new_json_and_manual_bytes_without_canonical_writes() {
        let _process_gate = PROCESS_PROBE_GATE.lock().unwrap();
        let root = std::env::temp_dir().join(format!("native-candidate-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(root.join("webinfo")).unwrap();
        let path = root.join("config.yaml");
        std::fs::write(
            &path,
            include_str!("../../../docs/rust/examples/native-managed-empty/config.yaml"),
        )
        .unwrap();
        std::fs::write(root.join("webinfo/special_upstream_groups.json"), b"[]").unwrap();
        let owner = ManagedStore::open(&root).unwrap();
        let changes = vec![
            (
                PathBuf::from("webinfo/special_upstream_groups.json"),
                Some(br#"[{"slot":50,"name":"new group"}]"#.to_vec()),
            ),
            (
                PathBuf::from("webinfo/upstream_overrides.json"),
                Some(
                    br#"{"special_upstream_50":[{"tag":"local","enabled":true,"protocol":"udp","addr":"127.0.0.1:15455"}]}"#
                        .to_vec(),
                ),
            ),
            (
                PathBuf::from("rule/special_50.txt"),
                Some(b"full:new.test\n".to_vec()),
            ),
        ];
        let candidate = owner.compile_candidate(&path, changes).unwrap();
        let profile = candidate.config().managed_profile.as_ref().unwrap();
        assert_eq!(profile.groups.len(), 1);
        assert!(
            candidate
                .config()
                .domain_set("special_manual_50")
                .unwrap()
                .matches("new.test")
        );
        let generated = candidate
            .files()
            .iter()
            .find(|(path, _)| path == Path::new("sub_config/special_groups.yaml"))
            .unwrap()
            .1
            .as_ref()
            .unwrap();
        assert_eq!(generated, profile.generated_yaml.as_bytes());
        assert_eq!(
            crate::special_groups::sha256(generated),
            profile.generated_sha256
        );
        assert_eq!(
            std::fs::read(root.join("webinfo/special_upstream_groups.json")).unwrap(),
            b"[]"
        );
        assert!(!root.join("rule/special_50.txt").exists());
        assert!(!root.join("sub_config/special_groups.yaml").exists());
        drop(owner);
        std::fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn corrupt_artifact_or_escaping_journal_fails_before_any_recovery_write() {
        let _process_gate = PROCESS_PROBE_GATE.lock().unwrap();
        for corruption in ["backup", "staged", "escape", "marker"] {
            let root = std::env::temp_dir().join(format!(
                "native-journal-corrupt-{}-{corruption}",
                std::process::id()
            ));
            let _ = std::fs::remove_dir_all(&root);
            std::fs::create_dir_all(root.join("webinfo")).unwrap();
            let groups = PathBuf::from("webinfo/special_upstream_groups.json");
            let overrides = PathBuf::from("webinfo/upstream_overrides.json");
            std::fs::write(root.join(&groups), b"old groups").unwrap();
            std::fs::write(root.join(&overrides), b"old overrides").unwrap();
            let mut owner = ManagedStore::open(&root).unwrap();
            owner
                .prepare(
                    0,
                    1,
                    vec![
                        (groups.clone(), Some(b"new groups".to_vec())),
                        (overrides.clone(), Some(b"new overrides".to_vec())),
                    ],
                )
                .unwrap();
            owner.replace_prepared().unwrap();
            let dir = root.join(JOURNAL_DIR);
            match corruption {
                "backup" => std::fs::write(dir.join("1.old"), b"corrupt").unwrap(),
                "staged" => std::fs::remove_file(dir.join("1.new")).unwrap(),
                "escape" => {
                    let mut journal: serde_json::Value =
                        serde_json::from_slice(&std::fs::read(dir.join("journal.json")).unwrap())
                            .unwrap();
                    journal["files"][1]["path"] = serde_json::json!("../outside.json");
                    std::fs::write(
                        dir.join("journal.json"),
                        serde_json::to_vec(&journal).unwrap(),
                    )
                    .unwrap();
                }
                "marker" => std::fs::write(dir.join("commit"), b"unrelated marker").unwrap(),
                _ => unreachable!(),
            }
            drop(owner);
            let mut restarted = ManagedStore::open(&root).unwrap();
            assert!(
                restarted.recover().is_err(),
                "{corruption} must fail closed"
            );
            assert_eq!(
                std::fs::read(root.join(&groups)).unwrap(),
                b"new groups",
                "no partial undo for {corruption}"
            );
            assert_eq!(
                std::fs::read(root.join(&overrides)).unwrap(),
                b"new overrides"
            );
            assert!(dir.exists(), "retain {corruption} evidence for repair");
            drop(restarted);
            std::fs::remove_dir_all(root).unwrap();
        }
    }

    #[test]
    fn precommit_external_edit_conflict_preserves_external_bytes_after_restart() {
        let _process_gate = PROCESS_PROBE_GATE.lock().unwrap();
        let root =
            std::env::temp_dir().join(format!("native-journal-conflict-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(root.join("webinfo")).unwrap();
        let path = PathBuf::from("webinfo/special_upstream_groups.json");
        std::fs::write(root.join(&path), b"old").unwrap();
        let mut owner = ManagedStore::open(&root).unwrap();
        owner
            .prepare(0, 1, vec![(path.clone(), Some(b"candidate".to_vec()))])
            .unwrap();
        std::fs::write(root.join(&path), b"external edit").unwrap();
        assert!(matches!(
            owner.replace_prepared(),
            Err(TransactionError::Conflict(_))
        ));
        drop(owner);
        let mut restarted = ManagedStore::open(&root).unwrap();
        restarted.recover().unwrap();
        assert_eq!(std::fs::read(root.join(&path)).unwrap(), b"external edit");
        drop(restarted);
        std::fs::remove_dir_all(root).unwrap();
    }

    #[cfg(unix)]
    #[test]
    fn sigkill_at_every_filesystem_boundary_recovers_whole_generation() {
        let _process_gate = PROCESS_PROBE_GATE.lock().unwrap();
        use std::os::unix::process::ExitStatusExt;
        let mut killed = 0;
        for boundary in 1..150 {
            let root = std::env::temp_dir().join(format!(
                "native-journal-kill-{}-{boundary}",
                std::process::id()
            ));
            let _ = std::fs::remove_dir_all(&root);
            std::fs::create_dir_all(root.join("webinfo")).unwrap();
            std::fs::write(root.join("webinfo/special_upstream_groups.json"), b"old").unwrap();
            let ready = root.join("ready");
            let mut child = std::process::Command::new(std::env::current_exe().unwrap())
                .args([
                    "--exact",
                    "transaction::tests::crash_writer_child",
                    "--ignored",
                    "--nocapture",
                ])
                .env("MOSDNS_TEST_CRASH_ROOT", &root)
                .env("MOSDNS_TEST_CRASH_AFTER", boundary.to_string())
                .stdout(std::process::Stdio::null())
                .stderr(std::process::Stdio::null())
                .spawn()
                .unwrap();
            let deadline = std::time::Instant::now() + std::time::Duration::from_secs(15);
            let finished = loop {
                if ready.exists() {
                    break None;
                }
                if let Some(status) = child.try_wait().unwrap() {
                    break Some(status);
                }
                if std::time::Instant::now() >= deadline {
                    child.kill().unwrap();
                    child.wait().unwrap();
                    panic!("crash child did not reach boundary {boundary}");
                }
                std::thread::sleep(std::time::Duration::from_millis(5));
            };
            if let Some(status) = finished {
                assert!(
                    status.success(),
                    "crash child exited before boundary {boundary}"
                );
                std::fs::remove_dir_all(root).unwrap();
                break;
            }
            let committed = std::fs::read(&ready).unwrap() == b"committed"
                || root.join(JOURNAL_DIR).join("commit").exists();
            assert!(
                std::process::Command::new("kill")
                    .args(["-KILL", &child.id().to_string()])
                    .status()
                    .unwrap()
                    .success()
            );
            assert_eq!(child.wait().unwrap().signal(), Some(9));
            killed += 1;
            let mut restarted = ManagedStore::open(&root).expect("SIGKILL releases writer lock");
            restarted
                .recover()
                .unwrap_or_else(|error| panic!("SIGKILL boundary {boundary}: {error}"));
            assert_eq!(
                std::fs::read(root.join("webinfo/special_upstream_groups.json")).unwrap(),
                if committed { b"new" } else { b"old" },
                "boundary {boundary}"
            );
            let generated = root.join("sub_config/special_groups.yaml");
            if committed {
                assert_eq!(std::fs::read(generated).unwrap(), b"new yaml");
            } else {
                assert!(
                    !generated.exists(),
                    "uncommitted new file at boundary {boundary}"
                );
            }
            restarted.recover().unwrap();
            drop(restarted);
            std::fs::remove_dir_all(root).unwrap();
        }
        assert!(
            killed >= 30,
            "must kill across preparation/replacement/marker/cleanup, got {killed}"
        );
        eprintln!("real SIGKILL/restart boundaries proved: {killed}");
    }

    #[test]
    #[ignore = "subprocess probe, invoked by SIGKILL recovery test"]
    fn crash_writer_child() {
        let _process_gate = PROCESS_PROBE_GATE.lock().unwrap();
        let root = PathBuf::from(std::env::var_os("MOSDNS_TEST_CRASH_ROOT").unwrap());
        let boundary = std::env::var("MOSDNS_TEST_CRASH_AFTER")
            .unwrap()
            .parse()
            .unwrap();
        let mut owner = ManagedStore::open(&root).unwrap();
        IO_PAUSE_PATH.with(|path| *path.borrow_mut() = Some(root.join("ready")));
        IO_FAIL_AFTER.with(|fault| fault.set(Some(boundary)));
        owner
            .prepare(
                0,
                1,
                vec![
                    (
                        PathBuf::from("webinfo/special_upstream_groups.json"),
                        Some(b"new".to_vec()),
                    ),
                    (
                        PathBuf::from("sub_config/special_groups.yaml"),
                        Some(b"new yaml".to_vec()),
                    ),
                ],
            )
            .unwrap();
        owner.replace_prepared().unwrap();
        owner.mark_committed().unwrap();
        IO_COMMITTED.with(|value| value.set(true));
        owner.finish_retirement().unwrap();
    }

    #[test]
    fn host_startup_recovers_before_compile_and_keeps_writer_owned_by_control() {
        let _process_gate = PROCESS_PROBE_GATE.lock().unwrap();
        let root =
            std::env::temp_dir().join(format!("native-journal-startup-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(root.join("webinfo")).unwrap();
        let config = root.join("config.yaml");
        std::fs::write(
            &config,
            include_str!("../../../docs/rust/examples/native-managed-empty/config.yaml"),
        )
        .unwrap();
        std::fs::write(root.join("webinfo/special_upstream_groups.json"), b"[]").unwrap();
        let mut owner = ManagedStore::open(&root).unwrap();
        owner
            .prepare(
                0,
                1,
                vec![(
                    PathBuf::from("webinfo/special_upstream_groups.json"),
                    Some(b"incomplete configuration".to_vec()),
                )],
            )
            .unwrap();
        owner.replace_prepared().unwrap();
        drop(owner);
        let host = crate::HostAssembly::from_config_file(&config)
            .expect("undo must precede configuration decode");
        let control = host.control();
        assert!(
            crate::HostAssembly::from_config_file(&config).is_err(),
            "second host writer must be refused before assembly"
        );
        drop(host);
        assert!(
            matches!(ManagedStore::open(&root), Err(TransactionError::Busy(_))),
            "control lifetime owns writer lock"
        );
        drop(control);
        drop(ManagedStore::open(&root).unwrap());
        std::fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn failure_at_each_filesystem_boundary_is_restart_recoverable() {
        let _process_gate = PROCESS_PROBE_GATE.lock().unwrap();
        let groups_path = PathBuf::from("webinfo/special_upstream_groups.json");
        let dump_path = PathBuf::from("cache/cache_all.dump");
        let old_dump = crate::cache_dump::encode(&[mosdns_cache_core::NativeSnapshotEntry {
            attachment: None,
            key: b"old-cache-key".to_vec(),
            response: b"old-cache-response".to_vec(),
            times: [1; 3],
            wall_times: Some([1, 1, 1]),
            domain_set: Vec::new(),
        }])
        .unwrap();
        let new_dump = crate::cache_dump::encode(&[]).unwrap();
        let allowed_cache_dumps = std::collections::BTreeSet::from([dump_path.clone()]);
        let mut injected = 0;
        for boundary in 1..100 {
            let root = std::env::temp_dir().join(format!(
                "native-journal-fault-{}-{boundary}",
                std::process::id()
            ));
            let _ = std::fs::remove_dir_all(&root);
            std::fs::create_dir_all(root.join("webinfo")).unwrap();
            std::fs::create_dir_all(root.join("cache")).unwrap();
            std::fs::write(root.join(&groups_path), b"old").unwrap();
            std::fs::write(root.join(&dump_path), &old_dump).unwrap();
            let mut owner = ManagedStore::open(&root).unwrap();
            IO_FAIL_AFTER.with(|fault| fault.set(Some(boundary)));
            let mut committed = false;
            let result = (|| {
                owner.prepare_with_inputs(
                    0,
                    1,
                    vec![
                        (groups_path.clone(), Some(b"new".to_vec())),
                        (dump_path.clone(), Some(new_dump.clone())),
                    ],
                    Vec::new(),
                    &allowed_cache_dumps,
                )?;
                owner.replace_prepared()?;
                owner.mark_committed()?;
                committed = true;
                owner.finish_retirement()
            })();
            IO_FAIL_AFTER.with(|fault| fault.set(None));
            if result.is_err() {
                injected += 1;
            }
            let marker = root.join(JOURNAL_DIR).join("commit").exists();
            drop(owner);
            let mut restarted = ManagedStore::open(&root).unwrap();
            restarted
                .recover()
                .unwrap_or_else(|error| panic!("boundary {boundary} did not recover: {error}"));
            let actual = std::fs::read(root.join(&groups_path)).unwrap();
            let expected_dump = if marker || committed || result.is_ok() {
                &new_dump
            } else {
                &old_dump
            };
            let actual_dump = std::fs::read(root.join(&dump_path)).unwrap();
            assert_eq!(
                actual_dump.as_slice(),
                expected_dump.as_slice(),
                "cache dump recovery at boundary {boundary}"
            );
            assert_eq!(
                crate::cache_dump::decode(&actual_dump).unwrap().len(),
                if marker || committed || result.is_ok() {
                    0
                } else {
                    1
                },
                "valid cache dump generation at boundary {boundary}"
            );
            if marker || committed || result.is_ok() {
                assert_eq!(actual, b"new", "committed boundary {boundary}");
            } else {
                assert_eq!(actual, b"old", "uncommitted boundary {boundary}");
            }
            drop(restarted);
            std::fs::remove_dir_all(root).unwrap();
            if result.is_ok() {
                break;
            }
        }
        assert!(
            injected >= 15,
            "filesystem matrix must exercise real write/rename/fsync/cleanup boundaries"
        );
    }

    #[test]
    fn durable_marker_recovers_new_state_even_if_canonical_files_are_torn() {
        let _process_gate = PROCESS_PROBE_GATE.lock().unwrap();
        let root = std::env::temp_dir().join(format!("native-journal-redo-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(root.join("webinfo")).unwrap();
        let file = root.join("webinfo/special_upstream_groups.json");
        std::fs::write(&file, b"old").unwrap();
        let mut owner = ManagedStore::open(&root).unwrap();
        owner
            .prepare(
                9,
                10,
                vec![(
                    PathBuf::from("webinfo/special_upstream_groups.json"),
                    Some(b"new".to_vec()),
                )],
            )
            .unwrap();
        owner.replace_prepared().unwrap();
        owner.mark_committed().unwrap();
        std::fs::write(&file, b"torn").unwrap();
        drop(owner);
        let mut restarted = ManagedStore::open(&root).unwrap();
        restarted.recover().unwrap();
        assert_eq!(std::fs::read(&file).unwrap(), b"new");
        restarted.recover().unwrap();
        drop(restarted);
        std::fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn uncommitted_replacement_recovers_every_original_file() {
        let _process_gate = PROCESS_PROBE_GATE.lock().unwrap();
        let root = std::env::temp_dir().join(format!("native-journal-undo-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(root.join("webinfo")).unwrap();
        std::fs::write(
            root.join("webinfo/special_upstream_groups.json"),
            b"old groups",
        )
        .unwrap();
        let mut owner = ManagedStore::open(&root).unwrap();
        owner
            .prepare(
                0,
                1,
                vec![
                    (
                        PathBuf::from("webinfo/special_upstream_groups.json"),
                        Some(b"new groups".to_vec()),
                    ),
                    (
                        PathBuf::from("sub_config/special_groups.yaml"),
                        Some(b"new generated yaml".to_vec()),
                    ),
                ],
            )
            .unwrap();
        owner.replace_prepared().unwrap();
        assert_eq!(
            std::fs::read(root.join("webinfo/special_upstream_groups.json")).unwrap(),
            b"new groups"
        );
        drop(owner);
        let mut restarted = ManagedStore::open(&root).unwrap();
        restarted.recover().unwrap();
        assert_eq!(
            std::fs::read(root.join("webinfo/special_upstream_groups.json")).unwrap(),
            b"old groups"
        );
        assert!(!root.join("sub_config/special_groups.yaml").exists());
        drop(restarted);
        std::fs::remove_dir_all(root).unwrap();
    }

    #[cfg(unix)]
    #[test]
    fn state_directory_symlink_cannot_write_outside_root() {
        let _process_gate = PROCESS_PROBE_GATE.lock().unwrap();
        let root =
            std::env::temp_dir().join(format!("native-writer-symlink-{}", std::process::id()));
        let outside = root.with_extension("outside");
        let _ = std::fs::remove_dir_all(&root);
        let _ = std::fs::remove_dir_all(&outside);
        std::fs::create_dir_all(&root).unwrap();
        std::fs::create_dir_all(&outside).unwrap();
        std::os::unix::fs::symlink(&outside, root.join("webinfo")).unwrap();
        assert!(ManagedStore::open(&root).is_err());
        assert!(!outside.join("native_management.lock").exists());
        std::fs::remove_dir_all(root).unwrap();
        std::fs::remove_dir_all(outside).unwrap();
    }

    #[test]
    fn writer_lock_refuses_an_independent_process_and_releases_on_drop() {
        let _process_gate = PROCESS_PROBE_GATE.lock().unwrap();
        let root = std::env::temp_dir().join(format!("native-writer-lock-{}", std::process::id()));
        std::fs::create_dir_all(&root).unwrap();
        let owner = ManagedStore::open(&root).unwrap();
        let child = |expected| {
            std::process::Command::new(std::env::current_exe().unwrap())
                .args([
                    "--exact",
                    "transaction::tests::writer_lock_child",
                    "--ignored",
                    "--nocapture",
                ])
                .env("MOSDNS_TEST_WRITER_ROOT", &root)
                .env("MOSDNS_TEST_WRITER_EXPECT", expected)
                .output()
                .unwrap()
        };
        let refused = child("busy");
        assert!(
            refused.status.success(),
            "second process must be refused: {}",
            String::from_utf8_lossy(&refused.stdout)
        );
        drop(owner);
        let reopened = child("open");
        assert!(
            reopened.status.success(),
            "writer drop must release the OS lock: {}",
            String::from_utf8_lossy(&reopened.stdout)
        );
        std::fs::remove_dir_all(root).unwrap();
    }

    #[test]
    #[ignore = "subprocess probe, invoked by writer-lock ownership test"]
    fn writer_lock_child() {
        let _process_gate = PROCESS_PROBE_GATE.lock().unwrap();
        let root = PathBuf::from(std::env::var_os("MOSDNS_TEST_WRITER_ROOT").unwrap());
        match std::env::var("MOSDNS_TEST_WRITER_EXPECT").unwrap().as_str() {
            "busy" => assert!(matches!(
                ManagedStore::open(&root),
                Err(TransactionError::Busy(_))
            )),
            "open" => {
                ManagedStore::open(&root).unwrap();
            }
            _ => panic!("invalid writer-lock probe expectation"),
        }
    }
}
