[workspace]
members = [
    "cache-core",
    "matcher-core",
    "dns-core",
    "sequence-core",
    "upstream-core",
    "runtime",
]
resolver = "3"

[workspace.package]
edition = "2024"
license = "GPL-3.0-only"
rust-version = "1.85"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[workspace.lints.clippy]
all = "deny"
pedantic = "deny"
