log: {level: error}
api: {http: '127.0.0.1:21980'}
plugins:
  - tag: ecs
    type: ecs_handler
    args: {send: true, mask4: 32}
  - tag: cache
    type: cache
    args: {enable_ecs: true, dump_file: cache.gz, lazy_cache_ttl: 900}
  - tag: supplier
    type: forward
    args: {upstreams: [{tag: controlled, addr: 'udp://127.0.0.1:21954'}]}
  - tag: main
    type: sequence
    args: [{exec: '$ecs'}, {exec: '$cache'}, {exec: '$supplier'}]
  - tag: dns
    type: tcp_server
    args: {entry: main, listen: '127.0.0.1:21953', enable_audit: true, idle_timeout: 10}
