log:
  level: error
api:
  http: 127.0.0.1:18080
plugins:
  - tag: upstream
    type: forward
    args:
      upstreams:
        - {tag: primary, addr: 'udp://127.0.0.1:15453'}
  - tag: entry
    type: sequence
    args:
      - exec: $upstream
  - tag: listener
    type: udp_server
    args:
      entry: entry
      listen: 127.0.0.1:15400
      enable_audit: true
